# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  facul-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: facul-mysql
    volumes:
      - facul-mysql-data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=facul
      - MYSQL_DATABASE=facul
      - MYSQL_USER=facul
      - MYSQL_PASSWORD=facul
      - UPLOAD_LIMIT=64M

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: facul-app
    depends_on:
      - mysql
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: facul-phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8182:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=facul
      - MYSQL_USER=facul
      - MYSQL_PASSWORD=facul
      - UPLOAD_LIMIT=64M
